apiVersion: v1
kind: Secret
metadata:
  name: movie-secret
  type: Opaque   
data:
  movie_db_username: movie_db_username # echo -n movie_db_username | base64
  movie_db_password: movie_db_password # echo -n movie_db_password | base64
