apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: movie-db
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgresMovie.image }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresMovie.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresMovie.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresMovie.password }}
        ports:
        - containerPort: 5432