apiVersion: v1
kind: Secret
metadata:
  name: cast-secret
  type: Opaque   
data:
  cast_db_username: cast_db_username # echo -n cast_db_username | base64
  cast_db_password: cast_db_password # echo -n cast_db_password | base64